bool obstacle_detected_rear_left    #TRUE for obstacle in rear left
bool obstacle_detected_rear_center  #TRUE for obstacle in rear center
bool obstacle_detected_rear_right   #TRUE for obstacle in rear right
bool obstacle_detected_front_left   #TRUE for obstacle in front left
bool obstacle_detected_front_center #TRUE for obstacle in front center
bool obstacle_detected_front_right  #TRUE for obstacle in front right

bool obstacle_detected_rear  #TRUE for car to stop moving backward
bool obstacle_detected_front #TRUE for car to stop moving forward